### ISSUE TITLE
Broken link (404) to Open Street Map in Week 1 Post

### ISSUE THREAD

**Issue by Eli10** [hunter-college-ossd-spr19/jch8ri-weekly#2]
Assuming that the Open StreetMap link was suppose to redirect to the website directly, however it return a 404 page. You made need to include https:// in the url for the link to redirect properly

<img width="1346" alt="screen shot 2019-02-21 at 8 59 55 pm" src="https://user-images.githubusercontent.com/18421625/53214742-bd551f00-361b-11e9-859c-f7c635b166eb.png">

**Comment by jch8ri** [comment]
Thanks! Fixed it!
